### ISSUE TITLE
Landscape or Portrait

### ISSUE THREAD

**Issue by dichen-cd** [guanyingc/PS-FCN_Poster_LaTex#1]
Hi there~

I was wondering which format would be formally used at the ECCV'18 site? Portrait or landscape? Didn't find any information on the official site. Would you like to share some information?

Thank you.

**Comment by guanyingc** [comment]
Hi,

I also have no idea which format would be used in the upcoming ECCV, so I provide poster examples in both formats. I believe the official website will add the Presenter Guidelines soon.

**Comment by dichen-cd** [comment]
Thank you very much!
